### ISSUE TITLE
Flexget integration

### ISSUE THREAD

**Issue by marine1988** [Tommatheussen/Home-Assistant-Configuration#32]
Hi there I try to use your flexget component is that still working? I try to use it but is just impossible tha gives me a lot off errors. Is there any way to fix it?

**Comment by Tommatheussen** [comment]
Which errors do you get?
I'm currently in between moving server stuff around, I've got it disabled, but a while ago it was still working.

**Comment by marine1988** [comment]
The binary sensors doen´t appear on home assistant!

**Comment by Tommatheussen** [comment]
Lol ok, I was hoping for some actual error message ;) 
But, I enabled it for my own installation just now, and indeed, it's failing, I will investigate today.

**Comment by Tommatheussen** [comment]
Can I ask how you configured you component?

**Comment by Tommatheussen** [comment]
Without knowing the actual issue, it might have been fixed in 491a538bb6a998956065fd8fba0d0dc5c4e2da10.
Configuration might have changed a bit: 
```yaml
binary_sensor:
  - platform: flexget
    host: http://localhost:5050 (optional, default)
    ssl: True (check cert, useful for polling local instance while behind proxy, default)
    password: **** (required)
```
